version: '4.26.1'
services:
  #MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: testpassword
      AUTH: admin
    ports:
      - 27018:27017
    volumes:
      - my_mongodb_data:/data/db

  #MongoExpress

volumes:
  my_mongodb_data:
    driver: local