PATCH http://localhost:4000/api/v2/articles/65c4ab758fcec4d262fd834f
Content-Type: application/json

[
    {
        "op": "replace",
        "path": "title",
        "value": "json patch"
    },
    {
        "op": "replace",
        "path": "body",
        "value": "json patch is a cool thing."
    },
    {
        "op": "add",
        "path": "tags",
        "value": "json"
    },
    {
        "op":"add",
        "path":"test1",
        "value":"test1"
    },
    {
        "op":"add",
        "path":"test2",
        "value":"test2"
    }
]

###

POST http://localhost:4000/api/v1/auth/register
Content-Type: application/json

{
  "name": "Tanzim",
  "email": "example@gmail.com",
  "password": "password123"
}