PATCH http://localhost:4000/api/v2/articles/65c4ab758fcec4d262fd834f
Content-Type: application/json

[
    {
        "op": "replace",
        "path": "title",
        "value": "json patch"
    },
    {
        "op": "replace",
        "path": "body",
        "value": "json patch is a cool thing."
    },
    {
        "op": "add",
        "path": "tags",
        "value": "json"
    },
    {
        "op":"add",
        "path":"test1",
        "value":"test1"
    },
    {
        "op":"add",
        "path":"test2",
        "value":"test2"
    }
]

###

POST http://localhost:4000/api/v1/auth/register
Content-Type: application/json

{
  "name": "Tanzim",
  "email": "example@gmail.com",
  "password": "password123"
}

###

POST http://localhost:4000/api/v1/auth/login
Content-Type: application/json

{
  "email": "example@gmail.com",
  "password": "password123"
}

###

POST http://localhost:4000/api/v1/articles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZDA2Zjc0NjU4MWNjZmViYjdjNTc4OSIsImVtYWlsIjoiZXhhbXBsZUBnbWFpbC5jb20iLCJuYW1lIjoiVGFuemltIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MDgxNzE3NjIsImV4cCI6MTcwODE3NTM2Mn0.cIBD-Cv4Ys1uPtuZ75Uf9N0YE-JnvQTLRgZzGeUULkk

{
  "title": "json patch 2",
  "body": "json patch is a cool thing.2",
  "tags": ["json"]
}

###

DELETE  http://localhost:4000/api/v1/articles/65bf968473da8f3982e763e0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZDA2Zjc0NjU4MWNjZmViYjdjNTc4OSIsImVtYWlsIjoiZXhhbXBsZUBnbWFpbC5jb20iLCJuYW1lIjoiVGFuemltIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MDgxNzE3NjIsImV4cCI6MTcwODE3NTM2Mn0.cIBD-Cv4Ys1uPtuZ75Uf9N0YE-JnvQTLRgZzGeUULkk
